config/routes.rb
LapencaUy::Application.routes.draw do
  devise_for :members, :controllers => {:registrations => 'registrations'}

  resources :matches, only: [:index, :show], path: 'resultados' do
    collection do
      resources :results, only: [:index, :create], path: 'actualizar'
    end
  end

  resources :points, only: [:index, :create], path: 'puntos' do
    collection do
      post 'recalcular', :action => 'recalculate'
    end
  end
  resources :forecasts, only: [:index, :create], path: 'pronostico'

  get 'reglas', to: 'static_pages#rules'

  root 'standings#show'
end

app/models/match.rb
class Match < ActiveRecord::Base
  #validates :date, presence: true

  belongs_to :team1, :class_name => 'Team'
  belongs_to :team2, :class_name => 'Team'
  has_many   :forecasts

  def winner
    raise 'Match score not entered' unless team1_score && team2_score
    if team1_score == team2_score
      winner_id ? Team.find(winner_id) : raise('Winner not entered')
    else
      team1_score > team2_score ? team1 : team2
    end
  end

  def draw?
    raise 'Match score not entered' unless team1_score && team2_score
    team1_score == team2_score
  end

  def result_sym
    if draw?
      :draw
    else
      if team1_score > team2_score
        :team1
      else
        :team2
      end
    end
  end

  def description
    "#{team1.try :name} #{team1_score || '*'} - #{team2_score || '*'} #{team2.try :name}"
  end

  def loser_id
    if winner_id == team1_id
      team2_id
    elsif winner_id == team2_id
      team1_id
    end
  end
end

app/controllers/matches_controller.rb
class MatchesController < ApplicationController
  def index
    @matches = Match.all
  end

  def show
  end
end

app/helpers/matches_helper.rb
module MatchesHelper
end

app/views/matches/_match.html.haml
%li
  .row.match
    .small-4.columns.team.left-team
      = match.team1.name
    = content_tag :div, match.try(:team1_score), class: ['small2', 'columns', 'team-score', 'group-stage', match.team1.name.downcase]
    = content_tag :div, match.try(:team2_score), class: ['small2', 'columns', 'team-score', 'group-stage', match.team2.name.downcase]
    .small-4.columns.team.right-team
      = match.team2.name

app/views/matches/_playoff_match.html.haml
.match
  = content_tag :div, class: 'team' do
    .name
      - if playoff_match.stage == 8
        = playoff_match.team1.try :name
    .score
      - if playoff_match.team1_score == playoff_match.team2_score && playoff_match.winner_id.present? && playoff_match.team1_id == playoff_match.winner_id
        = "#{playoff_match.try(:team1_score)}*"
      -else
        = playoff_match.try(:team1_score)
  = content_tag :div, class: 'team' do
    .name
      - if playoff_match.stage == 8
        = playoff_match.team2.try :name
    .score
      - if playoff_match.team1_score == playoff_match.team2_score && playoff_match.winner_id.present? && playoff_match.team2_id == playoff_match.winner_id
        = "#{playoff_match.try(:team2_score)}*"
      -else
        = playoff_match.try(:team2_score)

app/views/matches/_playoffs.html.haml
.row
  .playoffs
    -# OCTAVOS A
    .columns.stage.left-side
      .four
      .four
      .four
      .four

    -# CUARTOS A
    .columns.stage.left-side
      .two
        = render partial: 'playoff_match', object: @matches.where(stage: 8, pos_in_stage: 1).first
      .two
        = render partial: 'playoff_match', object: @matches.where(stage: 8, pos_in_stage: 2).first

    -# SEMIS A
    .columns.stage.left-side
      .one
        = render partial: 'playoff_match', object: @matches.where(stage: 4, pos_in_stage: 1).first

    -# FINAL
    .columns.stage.center-side
      .three
        = render partial: 'playoff_match', object: @matches.where(stage: 2, pos_in_stage: 1).first
      .three
        = render partial: 'playoff_match', object: @matches.where(stage: 2, pos_in_stage: 2).first

    -# SEMIS B
    .columns.stage.right-side
      .one
        = render partial: 'playoff_match', object: @matches.where(stage: 4, pos_in_stage: 2).first

    -# CUARTOS B
    .columns.stage.right-side
      .two
        = render partial: 'playoff_match', object: @matches.where(stage: 8, pos_in_stage: 3).first
      .two
        = render partial: 'playoff_match', object: @matches.where(stage: 8, pos_in_stage: 4).first

    -# OCTAVOS B
    .columns.stage.right-side
      .four
      .four
      .four
      .four

app/views/matches/index.html.haml
.forecasts-container
  .row
    - if current_member and current_member.is_admin
      = link_to 'Go to Update Results', results_path, class: ['button', 'save-forecast-btn']
      %br
  .row
    .groups
    - @matches.where(stage: 32).sort_by(&:pos_in_stage).group_by(&:group).sort_by { |group, _| group }.each do |group, matches|
      .group-panel
        .title="Group #{group}"
        .matches
          .content{id: "panel#{group}"}
            .row
              .small-7.columns
                = render partial: 'match', collection: matches, as: :match
              .small-5.columns
                - teams = Team.where(group: group)
                .positions
                  %table{data: {teams: teams.map { |t| t.name.downcase }}}
                    %tr.header
                      %th.team Team
                      %th pts
                      %th gf
                      %th gc
                    - teams.each do |team|
                      %tr
                        %td.team= team.name
                        %td.pts
                        %td.gf
                        %td.gc

  = render partial: 'playoffs'

:javascript
  fixture()