config/routes.rb
LapencaUy::Application.routes.draw do
  devise_for :members, :controllers => {:registrations => 'registrations'}

  resources :matches, only: [:index, :show], path: 'resultados' do
    collection do
      resources :results, only: [:index, :create], path: 'actualizar'
    end
  end

  resources :points, only: [:index, :create], path: 'puntos' do
    collection do
      post 'recalcular', :action => 'recalculate'
    end
  end
  resources :forecasts, only: [:index, :create], path: 'pronostico'

  get 'reglas', to: 'static_pages#rules'

  root 'standings#show'
end

app/views/layouts/_header.html.haml
%nav.top-bar{'data-topbar' => ''}
  %ul.title-area
    %li.name
      %h1
        = link_to 'CopaAmerica 2016', root_path
  %section.top-bar-section
    %ul.right
      %li
        = link_to 'Standings', root_path
      %li
        = link_to 'Forecast', forecasts_path
      %li
        = link_to 'Results', matches_path
      %li
        = link_to 'Rules', reglas_path
      %li.has-dropdown.active
        %a{href: "#"}
          = current_member.email
        %ul.dropdown
          %li
            = link_to 'Log Out', destroy_member_session_path, {method: 'delete'}

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title Copa America 2016
    = stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true
    = javascript_include_tag "application", "data-turbolinks-track" => true
    = csrf_meta_tags
  %body
    - if current_member
      = render 'layouts/header'
    - if notice
      .alert-box.success= notice
    - if alert
      .alert-box.alert= alert
    - if current_member
      .page-container
        = yield
    - else
      = yield